name: Android CI

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate app Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Generate app Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release APK
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk